### ISSUE TITLE
modelviewer.dev isn't showing previews for models

### ISSUE THREAD

**Issue by glued** [GoogleWebComponents/model-viewer#966]
Chrome dev tools reports:
Failed to load resource: the server responded with a status of 404 ()

For:
https://modelviewer.dev/node_modules/@google/model-viewer/dist/model-viewer.js

Which doesn't exist

**Comment by elalish** [comment]
@glued Thanks, I believe we just fixed this. Can you verify?

**Comment by konhoe** [comment]
Hi,
https://modelviewer.dev/examples/lighting-and-environment.html
still throws some 404s:
shared-assets/models/glTF-Sample-Models/2.0/MetalRoughSpheres/glTF/MetalRoughSpheres.gltf
shared-assets/models/glTF-Sample-Models/2.0/DamagedHelmet/glTF/DamagedHelmet.gltf

Thanks

**Comment by cdata** [comment]
@konhoe thanks for catching that, we'll get it fixed!

**Comment by glued** [comment]
appears to be fixed now
